# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging
namePrefix: staging-

labels:
  - includeSelectors: false
    pairs:
      environment: staging

patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: demo-app

configMapGenerator:
  - name: demo-app-config
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=staging
      - FEATURE_FLAG_NEW_UI=true