# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging
namePrefix: staging-

labels:
  - includeSelectors: false
    pairs:
      environment: staging

patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: demo-app
  - path: ingress-active-patch.yaml
    target:
      kind: Ingress
      name: demo-app


configMapGenerator:
  - name: demo-app-config
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=staging
      - FEATURE_FLAG_NEW_UI=true

# Da Aula 08 — troca o bloco de canary (Aula 07) por este
replacements:
  - source: {kind: Service, name: demo-app, fieldPath: metadata.name}
    targets:
      - select: {kind: Rollout}
        fieldPaths:
          - spec.strategy.blueGreen.activeService
  - source: {kind: Service, name: demo-app-preview, fieldPath: metadata.name}
    targets:
      - select: {kind: Rollout}
        fieldPaths:
          - spec.strategy.blueGreen.previewService
          - spec.strategy.blueGreen.prePromotionAnalysis.args.0.value
  - source: {kind: AnalysisTemplate, name: smoke-test-bluegreen, fieldPath: metadata.name}
    targets:
      - select: {kind: Rollout}
        fieldPaths:
          - spec.strategy.blueGreen.prePromotionAnalysis.templates.0.templateName
  - source: {kind: AnalysisTemplate, name: success-rate-active, fieldPath: metadata.name}
    targets:
      - select: {kind: Rollout}
        fieldPaths:
          - spec.strategy.blueGreen.postPromotionAnalysis.templates.0.templateName
  - source: {kind: Ingress, name: demo-app, fieldPath: metadata.name}
    targets:
      - select: {kind: Rollout}
        fieldPaths:
          - spec.strategy.blueGreen.postPromotionAnalysis.args.0.value